In [2]:
import pandas as pd
import numpy as np
import os
from sklearn.linear_model import LinearRegression

In [4]:
os.getcwd()

'C:\\Users\\FR'

In [5]:
# Change directory to where my CSV file resides
os.chdir("G:\\Project_for_modeling\\csv")

# Read the entire Excel files into a pandas DataFrame
MASHHAD = pd.read_excel('MASHHAD.xlsx')
TEHRAN = pd.read_excel('TEHRAN.xlsx')
ISFAHAN = pd.read_excel('ISFAHAN.xlsx')

In [6]:
ISFAHAN.head(5)

,OBJECTID0_12,OBJECTID_1,OSTAN,neigh_ID12,neigh_ID,district_ID,total _pop,migration,householders,rent,multi_family,single_family,Unnamed: 12,Unnamed: 13
0,1,300001,10,100,3100,اصفهان 1,1081,52,196,113,297,42,NaN,NaN
1,2,300002,10,100,3100,اصفهان 1,634,37,102,79,173,28,NaN,NaN
2,3,300003,10,100,3100,اصفهان 1,320,7,64,27,98,0,NaN,NaN
3,4,300004,10,100,3100,اصفهان 1,127,8,30,7,26,14,NaN,NaN
4,5,300005,10,100,3100,اصفهان 1,1028,81,183,123,293,29,NaN,NaN

In [7]:
# removing unwanted columns
ISFAHAN = ISFAHAN.drop(columns=['OBJECTID0_12','neigh_ID12'])

In [74]:
TEHRAN.head(5)

,OBJECTID_12,OBJECTID_1,OSTAN,neigh_ID12,neigh_ID,district_ID12,district_ID,total _pop,migration,householders,rent,multi_family,single_family
0,1,200001,23.0,202.0,2202,2.0,2002,NaN,NaN,NaN,NaN,NaN,NaN
1,2,200002,23.0,202.0,2202,2.0,2002,0.0,0.0,0.0,0.0,0.0,0.0
2,3,200003,23.0,202.0,2202,2.0,2002,0.0,0.0,0.0,0.0,0.0,0.0
3,4,200004,23.0,202.0,2202,2.0,2002,0.0,0.0,0.0,0.0,0.0,0.0
4,5,200005,23.0,208.0,2208,2.0,2002,175.0,12.0,43.0,15.0,57.0,1.0

In [8]:
# Remove common prefix from district_ID and convert to integer
ISFAHAN["district_ID"] = ISFAHAN["district_ID"].str.replace('اصفهان ', '').astype(int)

In [9]:
ISFAHAN = ISFAHAN.drop(columns=['Unnamed: 12', 'Unnamed: 13'])

In [10]:
MASHHAD = MASHHAD.drop(columns=['district_ID12'])

In [11]:
TEHRAN = TEHRAN.drop(columns=['OBJECTID_12', 'neigh_ID12', 'district_ID12'])

In [12]:
MASHHAD.tail(5)

,OBJECTID_1,OSTAN,neigh_ID,district_ID,total _pop,migration,householders,rent,multi_family,single_family
20102,108103,7,49,147008,160,4,22,22,43,9
20103,108104,7,77,147008,54,7,4,9,7,9
20104,108105,7,58,147008,131,5,22,11,17,18
20105,108106,7,73,147009,8431,7753,54,40,94,13
20106,108107,7,73,147009,8431,7753,54,40,94,13

In [13]:
#cleaning the data from outliers and missing values

ISFAHAN.replace("*", pd.NA, inplace=True)  # Convert "*" to pandas' missing value representation
MASHHAD.replace("*", pd.NA, inplace=True)  
TEHRAN.replace("*", pd.NA, inplace=True)

#remove raws with 0 value
ISFAHAN = ISFAHAN[ISFAHAN != 0].dropna()
MASHHAD = MASHHAD[MASHHAD != 0].dropna()
TEHRAN = TEHRAN[TEHRAN != 0].dropna()



# Drop rows with missing values
ISFAHAN.dropna(inplace=True)
MASHHAD.dropna(inplace=True)
TEHRAN.dropna(inplace=True)


# Reset index if needed
ISFAHAN.reset_index(drop=True, inplace=True)
MASHHAD.reset_index(drop=True, inplace=True)
TEHRAN.reset_index(drop=True, inplace=True)

In [14]:
# Convert other columns from string to integer
ISFAHAN["total _pop"] = ISFAHAN["total _pop"].astype(int)  # Example, replace with actual column names
# Convert other columns from string to integer
ISFAHAN["migration"] = ISFAHAN["migration"].astype(int)  # Example, replace with actual column names
# Convert other columns from string to integer
ISFAHAN["householders"] = ISFAHAN["householders"].astype(int)  # Example, replace with actual column names
# Convert other columns from string to integer
ISFAHAN["rent"] = ISFAHAN["rent"].astype(int)  # Example, replace with actual column names
ISFAHAN["multi_family"] = ISFAHAN["multi_family"].astype(int)  # Example, replace with actual column names
ISFAHAN["single_family"] = ISFAHAN["single_family"].astype(int)  # Example, replace with actual column names

In [15]:
# Merge the three data sets
data = pd.concat([ISFAHAN, MASHHAD, TEHRAN], ignore_index=True)

In [16]:
print (data)

       OBJECTID_1  OSTAN  neigh_ID  district_ID  total _pop  migration  \
0          300001   10.0      3100            1      1081.0       52.0
1          300002   10.0      3100            1       634.0       37.0
2          300003   10.0      3100            1       320.0        7.0
3          300004   10.0      3100            1       127.0        8.0
4          300005   10.0      3100            1      1028.0       81.0
...           ...    ...       ...          ...         ...        ...
47436      238585   23.0      2109         2001      1399.0      112.0
47437      238586   23.0      2109         2001       129.0       13.0
47438      238587   23.0      2109         2001       142.0        6.0
47439      238588   23.0      2109         2001       103.0        4.0
47440      238589   23.0      2109         2001      3276.0      199.0

       householders   rent  multi_family  single_family
0             196.0  113.0         297.0           42.0
1             102.0   79.0         173.0           28.0
2              64.0   27.0          98.0            0.0
3              30.0    7.0          26.0           14.0
4             183.0  123.0         293.0           29.0
...             ...    ...           ...            ...
47436         216.0  213.0         476.0           23.0
47437          22.0   15.0          39.0            2.0
47438          19.0   17.0          43.0            2.0
47439          12.0   21.0          37.0            1.0
47440         326.0  344.0         920.0           53.0

[47441 rows x 10 columns]

In [17]:
#  census data is in a DataFrame named "data"
data = data.set_index("OBJECTID_1")

# Now, "OBJECTID_1" columns acts as the index
print(data.head())

            OSTAN  neigh_ID  district_ID  total _pop  migration  householders  \
OBJECTID_1
300001       10.0      3100            1      1081.0       52.0         196.0
300002       10.0      3100            1       634.0       37.0         102.0
300003       10.0      3100            1       320.0        7.0          64.0
300004       10.0      3100            1       127.0        8.0          30.0
300005       10.0      3100            1      1028.0       81.0         183.0

             rent  multi_family  single_family
OBJECTID_1
300001      113.0         297.0           42.0
300002       79.0         173.0           28.0
300003       27.0          98.0            0.0
300004        7.0          26.0           14.0
300005      123.0         293.0           29.0

In [18]:
# Get column names
header = data.columns.tolist()

# Print header
print(header)

['OSTAN', 'neigh_ID', 'district_ID', 'total _pop', 'migration', 'householders', 'rent', 'multi_family', 'single_family']

In [19]:
#addinf a column with the number of native residents
data['native_2'] = data['total _pop'] - data['migration']

In [20]:
header = data.columns.tolist()

# Print header
print(header)

['OSTAN', 'neigh_ID', 'district_ID', 'total _pop', 'migration', 'householders', 'rent', 'multi_family', 'single_family', 'native_2']

In [21]:
# global H index for multi family/single family segregaton with formula from: Barros and Feitusa (2018)
# based on theils entropy with this original formula: H = Σ (pi * ln(pi / pavg))
# hierarchal structure of data: neigh_ID --> district_ID --> OSTAN
# we have three types of segregation: multifam/singlefam houses - rental/owned houses and also native/immigrant dwellers

# Step 1: Calculate total population (N) in the study area
total_population = data[['multi_family', 'single_family']].sum().sum()

# Step 2: Calculate proportion of each group (τm) in the study area
proportions_study_area = data[['multi_family', 'single_family']].sum() / total_population

# Step 3: Calculate total entropy of the study area (E)
E = np.sum(proportions_study_area * np.log2(1 / proportions_study_area))

# Step 4: Calculate entropy of each locality (Ej)
# Group data by district and neighborhood
grouped_by_district_neighborhood = data.groupby(['OSTAN', 'district_ID', 'neigh_ID'])

# Calculate Ej for each locality
Ej_values = []
for (ostan, district_id, neigh_id), group_data in grouped_by_district_neighborhood:
    # Calculate total population in the locality (Nj)
    total_population_locality = group_data[['multi_family', 'single_family']].sum().sum()
    
    # Calculate proportion of each group (τjm) in the locality
    proportions_locality = group_data[['multi_family', 'single_family']].sum() / total_population_locality
    
    # Calculate entropy of the locality (Ej)
    Ej = np.sum(proportions_locality * np.log2(1 / proportions_locality))
    Ej_values.append(Ej)

# Step 5: Calculate global H index
Nj_values = data.groupby(['OSTAN', 'district_ID', 'neigh_ID'])[['multi_family', 'single_family']].sum().sum(axis=1)
global_H_index = np.sum(Nj_values * (E - Ej_values)) / total_population

print("Global H Index:", global_H_index)

Global H Index: 0.12550212259304908

In [22]:
# local H index at the level of neighborhoods for multi family/ single family segregaion with formula from: Barros and Feitusa (2018)
# based on theils entropy formula: Hlocal= (Nj (E-E j))/EN)

# Step 1: Calculate total population (N) in the study area
total_population = data[['multi_family', 'single_family']].sum().sum()

# Step 2: Calculate proportion of each group (τm) in the study area
proportions_study_area = data[['multi_family', 'single_family']].sum() / total_population

# Step 3: Calculate total entropy of the study area (E)
E = np.sum(proportions_study_area * np.log2(1 / proportions_study_area))

# Step 4: Calculate entropy of each locality (Ej)
# Group data by district and neighborhood
grouped_by_district_neighborhood = data.groupby(['OSTAN', 'district_ID', 'neigh_ID'])

# Calculate Ej for each locality
Ej_values = []
for (ostan, district_id, neigh_id), group_data in grouped_by_district_neighborhood:
    # Calculate total population in the locality (Nj)
    total_population_locality = group_data[['multi_family', 'single_family']].sum().sum()
    
    # Calculate proportion of each group (τjm) in the locality
    proportions_locality = group_data[['multi_family', 'single_family']].sum() / total_population_locality
    
    # Calculate entropy of the locality (Ej)
    Ej = np.sum(proportions_locality * np.log2(1 / proportions_locality))
    Ej_values.append(Ej)

# Step 5: Calculate local H index for each locality
Nj_values = data.groupby(['OSTAN', 'district_ID', 'neigh_ID'])[['multi_family', 'single_family']].sum().sum(axis=1)
local_H_index = (Nj_values * (E - Ej_values)) / total_population

# Print or use the 'local_H_index' values for further analysis
print("Local H Index:")
print(local_H_index)

Local H Index:
OSTAN  district_ID  neigh_ID
7.0    147001       3          -0.000004
                    4          -0.000002
                    5           0.000189
                    25         -0.000053
                    34          0.000102
                                  ...
23.0   2021         4103       -0.000184
       2022         4201        0.000314
                    4202        0.000043
                    4203       -0.000002
                    4204        0.000957
Length: 346, dtype: float64

In [23]:
# the local H index at the districts scale for muutlifamily/single family house types segregation with formula from: Barros and Feitusa (2018)


# Step 1: Calculate total population (N) in the study area
total_population = data[['multi_family', 'single_family']].sum().sum()

# Step 2: Calculate proportion of each group (τm) in the study area
proportions_study_area = data[['multi_family', 'single_family']].sum() / total_population

# Step 3: Calculate total entropy of the study area (E)
E = np.sum(proportions_study_area * np.log2(1 / proportions_study_area))

# Step 4: Calculate entropy of each district (Ej)
# Group data by district
grouped_by_district = data.groupby(['OSTAN', 'district_ID'])

# Calculate Ej for each district
Ej_values = []
for (ostan, district_id), group_data in grouped_by_district:
    # Calculate total population in the district (Nj)
    total_population_district = group_data[['multi_family', 'single_family']].sum().sum()
    
    # Calculate proportion of each group (τjm) in the district
    proportions_district = group_data[['multi_family', 'single_family']].sum() / total_population_district
    
    # Calculate entropy of the district (Ej)
    Ej = np.sum(proportions_district * np.log2(1 / proportions_district))
    Ej_values.append(Ej)

# Step 5: Calculate local H index for each district
Nj_values = data.groupby(['OSTAN', 'district_ID'])[['multi_family', 'single_family']].sum().sum(axis=1)
local_H_index = (Nj_values * (E - Ej_values)) / total_population

# Print or use the 'local_H_index' values for further analysis
print("Local H Index at the district level:")
print(local_H_index)

Local H Index at the district level:
OSTAN  district_ID
7.0    147001         0.000498
       147002        -0.002502
       147003        -0.001787
       147004        -0.001637
       147005        -0.001059
       147006        -0.000476
       147007        -0.002047
       147008        -0.000655
       147009         0.002104
       147010         0.000561
       147011         0.001345
       147012         0.000942
       147020        -0.000092
10.0   1             -0.001589
       2             -0.001102
       3             -0.001690
       4             -0.002577
       5             -0.002007
       6             -0.001924
       7             -0.002279
       8             -0.003151
       9             -0.015962
       10            -0.003480
       11            -0.001183
       12            -0.000990
       13            -0.002207
       14            -0.001560
       15            -0.004085
23.0   2001           0.011766
       2002           0.018297
       2003           0.010552
       2004           0.015603
       2005           0.028794
       2006           0.007641
       2007           0.008398
       2008           0.009952
       2009           0.002241
       2010           0.006982
       2011           0.008822
       2012           0.002579
       2013           0.005194
       2014           0.008381
       2015           0.002347
       2016          -0.000376
       2017          -0.000104
       2018           0.001042
       2019           0.001617
       2020           0.001876
       2021           0.002540
       2022           0.001180
dtype: float64

In [24]:
# the local H index at the city scale for muutlifamily/single family house types segregation
# Step 1: Calculate total population (N) in the study area
total_population = data[['multi_family', 'single_family']].sum().sum()

# Step 2: Calculate proportion of each group (τm) in the study area
proportions_study_area = data[['multi_family', 'single_family']].sum() / total_population

# Step 3: Calculate total entropy of the study area (E)
E = np.sum(proportions_study_area * np.log2(1 / proportions_study_area))

# Step 4: Calculate entropy of each district (Ej)
# Group data by district
grouped_by_district = data.groupby(['OSTAN'])

# Calculate Ej for each district
Ej_values = []
for (ostan), group_data in grouped_by_district:
    # Calculate total population in the district (Nj)
    total_population_district = group_data[['multi_family', 'single_family']].sum().sum()
    
    # Calculate proportion of each group (τjm) in the district
    proportions_district = group_data[['multi_family', 'single_family']].sum() / total_population_district
    
    # Calculate entropy of the district (Ej)
    Ej = np.sum(proportions_district * np.log2(1 / proportions_district))
    Ej_values.append(Ej)

# Step 5: Calculate local H index for each district
Nj_values = data.groupby(['OSTAN'])[['multi_family', 'single_family']].sum().sum(axis=1)
local_H_index = (Nj_values * (E - Ej_values)) / total_population

# Print or use the 'local_H_index' values for further analysis
print("Local H Index at the city level:")
print(local_H_index)

Local H Index at the city level:
OSTAN
7.0    -0.020072
10.0   -0.046551
23.0    0.139152
dtype: float64

In [58]:
# local H index at neighborhood level with formula from: Barros and Feitusa (2018) for three categories of entropy


# Step 1: Calculate total population (N) in the study area
total_population1 = data[['multi_family', 'single_family']].sum().sum()
total_population2 = data[[ 'native_2', 'migration', ]].sum().sum()
total_population3 = data[[ 'householders', 'rent']].sum().sum()

# Step 2: Calculate proportion of each group (τm) in the study area
proportions_study_area1 = data[['multi_family', 'single_family']].sum() / total_population1
proportions_study_area2 = data[[ 'native_2', 'migration']].sum() / total_population2
proportions_study_area3 = data[[ 'householders', 'rent']].sum() / total_population3

# Step 3: Calculate total entropy of the study area (E)
E1 = np.sum(proportions_study_area1 * np.log2(1 / proportions_study_area1))
E2 = np.sum(proportions_study_area2 * np.log2(1 / proportions_study_area2))
E3 = np.sum(proportions_study_area3 * np.log2(1 / proportions_study_area3))

# Step 4: Calculate entropy of each locality (Ej)
# Group data by district, neighborhood, and OSTAN(city)
grouped_by_ostan_district_neighborhood = data.groupby(['OSTAN', 'district_ID', 'neigh_ID'])

# Calculate Ej for each locality
local_H_index_dict = {}
for (ostan, district_id, neigh_id), group_data in grouped_by_ostan_district_neighborhood:
    # Calculate total population in the locality (Nj)
    total_population_locality1 = group_data[['multi_family', 'single_family']].sum().sum()
    total_population_locality2 = group_data[['native_2', 'migration']].sum().sum()
    total_population_locality3 = group_data[['householders', 'rent']].sum().sum()

    # Calculate proportion of each group (τjm) in the locality
    proportions_locality1 = group_data[['multi_family', 'single_family']].sum() / total_population_locality1
    proportions_locality2 = group_data[['native_2', 'migration']].sum() / total_population_locality2
    proportions_locality3 = group_data[['householders', 'rent']].sum() / total_population_locality3
    
    # Calculate entropy of the locality (Ej)
    Ej1 = np.sum(proportions_locality1 * np.log2(1 / proportions_locality1))
    Ej2 = np.sum(proportions_locality2 * np.log2(1 / proportions_locality2))
    Ej3 = np.sum(proportions_locality3 * np.log2(1 / proportions_locality3))

    # Calculate local H index for the locality
    Nj1 = group_data[['multi_family', 'single_family']].sum().sum()
    local_H_index1 = (Nj1 * (E1 - Ej1)) / total_population
    Nj2 = group_data[['native_2', 'migration']].sum().sum()
    local_H_index2 = (Nj2 * (E2 - Ej2)) / total_population
    Nj3 = group_data[[ 'householders', 'rent']].sum().sum()
    local_H_index3 = (Nj3 * (E3 - Ej3)) / total_population

    # Store the results in the dictionary
    local_H_index_dict[(ostan, district_id, neigh_id)] = {
        'city': data['OSTAN'],
        'district': data['district_ID'],
        'neighborhood': data['neigh_ID'],
        'local_H_index_multi/single': local_H_index1,
        'local_H_index_ethnic': local_H_index2,
        'local_H_index3_owned/rental': local_H_index3
    }

# Print or use the 'local_H_index_dict' for further analysis
#print("Local H Index Dictionary:")
#for key, value in local_H_index_dict.items():
#    print(key, value)

In [59]:
# making a data frame from the above dictionary
neighborhood_df = pd.DataFrame.from_dict(local_H_index_dict, orient='index')

In [61]:
header = neighborhood_df.columns.tolist()

# Print header
print(header)

['city', 'district', 'neighborhood', 'local_H_index_multi/single', 'local_H_index_ethnic', 'local_H_index3_owned/rental']

In [ ]:
output_path = r"G:\Project_for_modeling\csv\output.csv"

In [ ]:
# saving data frame in csv format
df.to_csv(output_path, index= False)

In [65]:
# to calculate entropy at neighborhood scale with shannons entropy
# with this formula: H(p) = - Σ (pi * log2(pi))


# Define function to calculate entropy
def calculate_entropy(proportions):
    # Clip proportions to avoid log of 0 or 1
    epsilon = 1e-10
    proportions = proportions.clip(epsilon, 1 - epsilon)

    # Calculate entropy using proportions
    entropy = -np.sum(proportions * np.log2(proportions))

    return entropy

# Group data by OSTAN, district_ID, and neigh_ID
grouped_by_location = data.groupby(['OSTAN', 'district_ID', 'neigh_ID'])

# Initialize dictionary to store entropies
entropies_dict = {}

# Iterate through each location group
for (ostan, district_id, neigh_id), group_data in grouped_by_location:
    # Calculate proportions for each category
    proportions_owned_rent = group_data[['multi_family', 'single_family']].sum() / group_data[['multi_family', 'single_family']].sum().sum()
    proportions_native_migration = group_data[['native_2', 'migration']].sum() / group_data[['native_2', 'migration']].sum().sum()
    proportions_householders_renters = group_data[['householders', 'rent']].sum() / group_data[['householders', 'rent']].sum().sum()

    # Calculate entropies for each category
    entropy_owned_rent = calculate_entropy(proportions_owned_rent)
    entropy_native_migration = calculate_entropy(proportions_native_migration)
    entropy_householders_renters = calculate_entropy(proportions_householders_renters)

    # Store entropies along with OSTAN and district_ID in the dictionary
    entropies_dict[(ostan, district_id, neigh_id)] = {
        'OSTAN': ostan,
        'district_ID': district_id,
        'neigh_ID': neigh_id,
        'entropy_multi_single': entropy_owned_rent,
        'entropy_native_migration': entropy_native_migration,
        'entropy_householders_renters': entropy_householders_renters
    }

# Convert dictionary to DataFrame
entropies_df0 = pd.DataFrame.from_dict(entropies_dict, orient='index')

print (entropies_df0)

                  OSTAN  district_ID  neigh_ID  entropy_multi_single  \
7.0  147001 3       7.0       147001         3              0.851329
            4       7.0       147001         4              0.848522
            5       7.0       147001         5              0.462850
            25      7.0       147001        25              0.999991
            34      7.0       147001        34              0.680231
...                 ...          ...       ...                   ...
23.0 2021   4103   23.0         2021      4103              0.981105
     2022   4201   23.0         2022      4201              0.671981
            4202   23.0         2022      4202              0.796359
            4203   23.0         2022      4203              0.852944
            4204   23.0         2022      4204              0.391581

                  entropy_native_migration  entropy_householders_renters
7.0  147001 3                     0.290177                      0.923156
            4                     0.299689                      0.989222
            5                     0.241131                      0.951113
            25                    0.282543                      0.999342
            34                    0.226507                      0.956227
...                                    ...                           ...
23.0 2021   4103                  0.381995                      0.999364
     2022   4201                  0.248819                      0.999723
            4202                  0.331286                      0.999918
            4203                  0.334580                      0.999595
            4204                  0.260886                      0.998958

[346 rows x 6 columns]

In [66]:
header = entropies_df0.columns.tolist()

# Print header
print(header)

['OSTAN', 'district_ID', 'neigh_ID', 'entropy_multi_single', 'entropy_native_migration', 'entropy_householders_renters']

In [63]:
# to calculate entropy at district scale with shannons entropy

def calculate_entropy(proportions):
    # Clip proportions to avoid log of 0 or 1
    epsilon = 1e-10
    proportions = proportions.clip(epsilon, 1 - epsilon)

    # Calculate entropy using proportions
    entropy = -np.sum(proportions * np.log2(proportions))

    return entropy

# Group data by OSTAN, district_ID, and neigh_ID
grouped_by_location = data.groupby(['OSTAN', 'district_ID'])

# Initialize dictionary to store entropies
entropies_dict = {}

# Iterate through each location group
for (ostan, district_id), group_data in grouped_by_location:
    # Calculate proportions for each category
    proportions_owned_rent = group_data[['multi_family', 'single_family']].sum() / group_data[['multi_family', 'single_family']].sum().sum()
    proportions_native_migration = group_data[['native_2', 'migration']].sum() / group_data[['native_2', 'migration']].sum().sum()
    proportions_householders_renters = group_data[['householders', 'rent']].sum() / group_data[['householders', 'rent']].sum().sum()

    # Calculate entropies for each category
    entropy_owned_rent = calculate_entropy(proportions_owned_rent)
    entropy_native_migration = calculate_entropy(proportions_native_migration)
    entropy_householders_renters = calculate_entropy(proportions_householders_renters)

    # Store entropies along with OSTAN and district_ID in the dictionary
    entropies_dict[(ostan, district_id)] = {
        'OSTAN': ostan,
        'district_ID': district_id,
        'entropy_multi_single': entropy_owned_rent,
        'entropy_native_migration': entropy_native_migration,
        'entropy_householders_renters': entropy_householders_renters
    }

# Convert dictionary to DataFrame
entropies_df1 = pd.DataFrame.from_dict(entropies_dict, orient='index')

print (entropies_df1)

             OSTAN  district_ID  entropy_multi_single  \
7.0  147001    7.0       147001              0.783843
     147002    7.0       147002              0.935376
     147003    7.0       147003              0.937414
     147004    7.0       147004              0.968965
     147005    7.0       147005              0.979545
     147006    7.0       147006              0.887969
     147007    7.0       147007              0.997215
     147008    7.0       147008              0.974968
     147009    7.0       147009              0.718706
     147010    7.0       147010              0.804306
     147011    7.0       147011              0.723180
     147012    7.0       147012              0.519559
     147020    7.0       147020              0.982952
10.0 1        10.0            1              0.991141
     2        10.0            2              0.967865
     3        10.0            3              0.981564
     4        10.0            4              0.985981
     5        10.0            5              0.979145
     6        10.0            6              0.990339
     7        10.0            7              0.991221
     8        10.0            8              0.980785
     9        10.0            9              0.969719
     10       10.0           10              0.991137
     11       10.0           11              0.981696
     12       10.0           12              0.928058
     13       10.0           13              0.989395
     14       10.0           14              0.963452
     15       10.0           15              0.946863
23.0 2001     23.0         2001              0.401361
     2002     23.0         2002              0.322997
     2003     23.0         2003              0.319189
     2004     23.0         2004              0.551122
     2005     23.0         2005              0.231971
     2006     23.0         2006              0.242496
     2007     23.0         2007              0.447764
     2008     23.0         2008              0.486073
     2009     23.0         2009              0.639234
     2010     23.0         2010              0.531184
     2011     23.0         2011              0.403188
     2012     23.0         2012              0.652621
     2013     23.0         2013              0.497609
     2014     23.0         2014              0.567465
     2015     23.0         2015              0.778042
     2016     23.0         2016              0.872065
     2017     23.0         2017              0.850351
     2018     23.0         2018              0.801103
     2019     23.0         2019              0.731057
     2020     23.0         2020              0.747592
     2021     23.0         2021              0.577205
     2022     23.0         2022              0.608143

             entropy_native_migration  entropy_householders_renters
7.0  147001                  0.244939                      0.968891
     147002                  0.257998                      0.999321
     147003                  0.266465                      0.995680
     147004                  0.233297                      0.991170
     147005                  0.219782                      0.987265
     147006                  0.256534                      0.998895
     147007                  0.285044                      0.995714
     147008                  0.288527                      0.995950
     147009                  0.536885                      0.999207
     147010                  0.329312                      0.998093
     147011                  0.274949                      0.996350
     147012                  0.389418                      0.977136
     147020                  0.392782                      0.999832
10.0 1                       0.238617                      0.994642
     2                       0.294868                      0.949613
     3                       0.229405                      0.959602
     4                       0.373551                      0.968390
     5                       0.231200                      0.955728
     6                       0.197860                      0.968131
     7                       0.258294                      0.965710
     8                       0.241551                      0.970987
     9                       0.260271                      0.977528
     10                      0.240965                      0.994041
     11                      0.267199                      0.993116
     12                      0.271909                      0.990453
     13                      0.249959                      0.982693
     14                      0.247060                      0.982092
     15                      0.240471                      0.961244
23.0 2001                    0.290882                      0.958303
     2002                    0.326748                      0.966764
     2003                    0.281955                      0.944190
     2004                    0.242461                      0.999971
     2005                    0.286574                      0.992683
     2006                    0.454309                      0.963206
     2007                    0.267947                      0.995870
     2008                    0.249977                      0.997696
     2009                    0.369092                      0.999701
     2010                    0.326983                      0.999979
     2011                    0.348154                      0.998962
     2012                    0.266745                      0.999367
     2013                    0.213988                      0.986608
     2014                    0.235207                      0.996294
     2015                    0.229554                      0.998928
     2016                    0.192442                      0.996632
     2017                    0.257157                      0.999581
     2018                    0.271923                      0.999992
     2019                    0.269444                      0.999938
     2020                    0.267282                      0.998522
     2021                    0.314932                      0.997096
     2022                    0.272977                      0.999970

In [64]:
header = entropies_df1.columns.tolist()

# Print header
print(header)

['OSTAN', 'district_ID', 'entropy_multi_single', 'entropy_native_migration', 'entropy_householders_renters']

In [30]:
# to calculate entropy at city scale with shannons entropy

def calculate_entropy(proportions):
    # Clip proportions to avoid log of 0 or 1
    epsilon = 1e-10
    proportions = proportions.clip(epsilon, 1 - epsilon)

    # Calculate entropy using proportions
    entropy = -np.sum(proportions * np.log2(proportions))

    return entropy

# Group data by OSTAN, district_ID, and neigh_ID
grouped_by_location = data.groupby(['OSTAN'])

# Initialize dictionary to store entropies
entropies_dict = {}

# Iterate through each location group
for (ostan), group_data in grouped_by_location:
    # Calculate proportions for each category
    proportions_owned_rent = group_data[['multi_family', 'single_family']].sum() / group_data[['multi_family', 'single_family']].sum().sum()
    proportions_native_migration = group_data[['native_2', 'migration']].sum() / group_data[['native_2', 'migration']].sum().sum()
    proportions_householders_renters = group_data[['householders', 'rent']].sum() / group_data[['householders', 'rent']].sum().sum()

    # Calculate entropies for each category
    entropy_owned_rent = calculate_entropy(proportions_owned_rent)
    entropy_native_migration = calculate_entropy(proportions_native_migration)
    entropy_householders_renters = calculate_entropy(proportions_householders_renters)

    # Store entropies along with OSTAN and district_ID in the dictionary
    entropies_dict[(ostan)] = {
        'OSTAN': ostan,
        'entropy_multi_single': entropy_owned_rent,
        'entropy_native_migration': entropy_native_migration,
        'entropy_householders_renters': entropy_householders_renters
    }

# Convert dictionary to DataFrame
entropies_df = pd.DataFrame.from_dict(entropies_dict, orient='index')

print (entropies_df)

        OSTAN  entropy_multi_single  entropy_native_migration  \
7.0    (7.0,)              0.977378                  0.306342
10.0  (10.0,)              0.974912                  0.257629
23.0  (23.0,)              0.562248                  0.278551

      entropy_householders_renters
7.0                       0.999448
10.0                      0.976115
23.0                      0.996009

In [68]:
# I used neighborhood_df.index instead of neigh_ID

# Function to calculate Theil Index
def theil_index(data, entropy_col, grouping_col):
  """
  Calculates the Theil Index for a given variable within groups.

  Args:
      data (pandas.DataFrame): The DataFrame containing the data.
      entropy_col (str): The column name containing the entropy values.
      grouping_col (str): The column name defining the groups for aggregation.

  Returns:
      float: The Theil Index value.
  """
  total_population = entropies_df0.shape[0]
  weighted_variance = sum(((entropies_df0.groupby(grouping_col)[entropy_col].count() / total_population) *
                         ((np.array(entropies_df0.groupby(grouping_col)[entropy_col].mean()) - data[entropy_col].mean())**2)))

  return weighted_variance

# Assuming 'city' column identifies city membership
city_membership = entropies_df0['OSTAN']
district_membership = entropies_df0['district_ID']

# Calculate total Theil Index
total_theil_index = theil_index(entropies_df0, 'entropy_multi_single', 'district_ID')

# Calculate Theil Index between all neighborhoods
neighborhood_theil_index = theil_index(entropies_df0, 'entropy_multi_single', 'neigh_ID')

# Calculate Theil Index between all places (excluding City 1) as it was a wrong data
place_theil_index = theil_index(entropies_df0[city_membership != 1], 'entropy_multi_single', 'OSTAN')

# Calculate Theil Index between all districts
district_theil_index = theil_index(entropies_df0[district_membership != 1], 'entropy_multi_single', 'district_ID')

# Calculate Theil Index between central city and suburbs (assuming separate groups)
city_suburb_theil_index = theil_index(entropies_df0[city_membership.isin([0, 1])], 'entropy_multi_single', 'OSTAN')

# Proportion of between-neighborhood due to between-place
prop_neighborhood_between_place = (neighborhood_theil_index - place_theil_index) / total_theil_index

# Proportion of between-neighborhood due to between-districts
prop_neighborhood_between_districts = (neighborhood_theil_index - district_theil_index) / total_theil_index


# Proportion of overall segregation due to central city vs suburbs
prop_city_suburb_overall = (city_suburb_theil_index - min(place_theil_index, neighborhood_theil_index - place_theil_index)) / total_theil_index

# Print results
print(f"Total Theil Index (for Entropy (ethnics)): {total_theil_index}")
print(f"Theil Index between Neighborhoods: {neighborhood_theil_index}")
print(f"Theil Index between cities: {place_theil_index}")
print(f"Theil Index between districts: {district_theil_index}")
#print(f"Theil Index between Central City and Suburbs: {city_suburb_theil_index}")
print(f"Proportion of Between-Neighborhood due to Between-cities: {prop_neighborhood_between_place}")
print(f"Proportion of Between-Neighborhood due to Between-districts: {prop_neighborhood_between_districts}")
#print(f"Proportion of Overall Segregation due to Central City vs Suburbs: {prop_city_suburb_overall}")

Total Theil Index (for Entropy (ethnics)): 0.04591443872084402
Theil Index between Neighborhoods: 0.053607704434707
Theil Index between cities: 0.029117326325019233
Theil Index between districts: 0.045918560937714244
Proportion of Between-Neighborhood due to Between-cities: 0.5333916474202643
Proportion of Between-Neighborhood due to Between-districts: 0.16746678629226222